### ISSUE TITLE
It seams that `Put on market` it's linked to the buying process instead of the selling process

### ISSUE THREAD

**Issue by cybercent** [dapperlabs/kitty-items-web#15]
`Put on market for 10.0 Kibble` redirects to Dapper Wallet (as it should) but instead of asking me to validate the TX it asks me to purchase.

<img width="612" alt="Screenshot 2021-01-05 at 13 52 55" src="https://user-images.githubusercontent.com/195806/103649016-0c7d7200-4f5e-11eb-944c-72bfb99ab49d.png">

**Comment by orodio** [comment]
@cybercent Dapper is doing all sorts of stuff with their testnet wallet. Should avoid it for the near future. This is a known thing and is the responsibility of Dapper and doesnt actually have anything to do with this stuff. So going to close this.
